name = "BayesianBlockModels"
uuid = "0e3e024e-b17e-4bfa-8dcb-a55950e8e86c"
authors = ["Aidan Gleich"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
